version: '3.9'

services:
  db:
    container_name:  mongodb-curvaderio
    image: mongo:7.0
#    ports:
#      - "27017:27017"
    network_mode: host
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '300MB'

networks:
  app-network: