version: '3.9'
name: 'rinha-de-backend-2'

#  1.5 CPUs =   0.6 MongoDB +   2 x     0.45 Spring Boot +     0.2 NGinx
#  550MB = 300MB MongoDB + 2 x 115MB Spring Boot + 20MB NGinx

services:
  spring-api1: &api
    image: docker.io/library/curva-de-rio:0.0.1-SNAPSHOT  # com GraalVM
#    image: docker.io/boaglio/curva-de-rio:latest  # sem GraalVM
    hostname: spring-api1
    network_mode: host
    environment:
      - SERVER_PORT=8081
      - MONGO_URI=mongodb://localhost:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=10&minPoolSize=5
    depends_on:
      - db
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '115MB'

  spring-api2:
    <<: *api
    hostname: spring-api2
    environment:
      - SERVER_PORT=8082
      - MONGO_URI=mongodb://localhost:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=10&minPoolSize=5
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'

  db:
    image: mongo:7-jammy
    hostname: db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '300MB'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
